### ISSUE TITLE
Sleep.

### ISSUE THREAD

**Issue by GeneTv** [janic0/sleep#1]
Sleep is a very important part of the life. It is required to sleep if you wish to survive for longer.

**Comment by janic0** [comment]
The more you sleep, the less time you have being conscious on a day-to-day basis. Sleeping longer might help you in increasing the age of your death, but that does not necessarily mean that the time you were active is greater than if you slept just one hour less per day. In the long term, you are just stretching your lifespan without increasing the time you could be leveraging as a human being.

**Comment by GeneTv** [comment]
This decision is very good!
